container:
  image: node:11


task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install

    matrix:
    - name: Lint
      lint_script: yarn run lint
    - name: Test
      test_script: yarn run test
    - name: Build
      depends_on:
        - Lint
        - Test
      only_if: $BRANCH == "master"
      publish_script: yarn run build