container:
  image: node:latest

check_task:
  lint_script: yarn lint

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  test_script: yarn test